### ISSUE TITLE
Obtain "compatible with GitHub Enterprise" approval

### ISSUE THREAD

**Issue by rarkins** [renovateapp/github-app-cli#10]
Renovate *works* with Github Enterprise, but apparently needs some rubber stamp from GitHub to show up as Enterprise-compatible in searches, as mentioned in https://github.com/renovateapp/renovate/issues/1497

**Comment by gtramontina** [comment]
Apparently it is already being displayed as [compatible](github.com/works-with?utf8=%E2%9C%93&query=renovate&enterprise_compatible=on).

<img width="774" alt="screen shot 2018-03-22 at 2 01 19 pm" src="https://user-images.githubusercontent.com/374635/37748908-9e1ba46a-2dd9-11e8-8162-e8c9fb7ba54f.png">
