### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/github-app-cli#116]
Found out that the `/installation/repositories` end-point only returns the first 30 repositories. Setting a hard-coded value for `per_page` will return more.

Looking into what it would take to add pagination support.

**Comment by destroyerofbuilds** [comment]
Oddly, there is no `Link` header in the response. No indication that additional repositories can be fetched.

**Comment by rarkins** [comment]
maybe adding `per_page=100` will mitigate for now?

**Comment by destroyerofbuilds** [comment]
> maybe adding per_page=100 will mitigate for now?

I can confirm that works.

I didn't want to submit a PR for that because it seemed like such a hack.

It looks like the only workaround is to look at the value of `total_count`, and re-issue the request with `per_page` set to that value.

However that may not work if the total count is over 1000 since other GitHub API end-points have a 1000 limit.

**Comment by destroyerofbuilds** [comment]
I can confirm that `?page=2&per_page=20` for paginating works.

So maybe setting `per_page` to a given number and paginate until you can retrieve the total number of repositories reported in the `total_count` property.

**Comment by rarkins** [comment]
GitHub recommends not contracting paginated URLs by hand. I prefer per_page=100 for now

**Comment by destroyerofbuilds** [comment]
May I set it to `500`? We have a mono-org that is just shy of that number, and growing.

**Comment by rarkins** [comment]
I think 100 is max they honour. I have pagination built into my GitHub wrapper in renovate itself that could be reused but only if we work out why the response doesn’t include pagination headers

________________________________

**Comment by destroyerofbuilds** [comment]
> I think 100 is max they honour.

For my benefit, I need to remember to check the maximum documented here - https://developer.github.com/v3/#pagination

> I have pagination built into my GitHub wrapper

Actually, that's what I was hoping to do, which is why I was confirming that the `Link` header was available (which lead me to finding out that the `Link` header isn't available.).

I'm filing an upstream support request with GHE to look into the issue.

**Comment by destroyerofbuilds** [comment]
In the meantime, let me submit a PR to bump the `per_page` to 100

**Comment by destroyerofbuilds** [comment]
After several repeated tests, I now see `link` headers:

```
link: '<https://github.example.com/api/v3/installation/repositories?page=2>; rel="next", <https://github.example.com/api/v3/installation/repositories?page=2>; rel="last"',
```

I honestly don't know why console logging headers earlier was not showing the `link` header.

I guess at this point the pagination code from Renovate could be used here to fetch all available repositories.
