### ISSUE TITLE
Custom Initial On-board Configuration

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/github-app-cli#12]
We would like to customize the configuration that is scaffolded into projects as part of the _Configure Renovate_ pull request workflow.

Specifically we would like to replace:

```json
{
  "extends": ["config:base"]
}
```

With:

```json
{
  "extends": ["config:base", ":preserveSemverRanges"]
}
```

We can [modify Renovate's](https://github.com/renovateapp/renovate/blob/d66dea7ec3cecc4323d3ced0e362ab7fa4868c6d/lib/workers/repository/onboarding/branch/create.js#L4) `branch` logic, but we would prefer a method that does not require maintaining a fork while still allowing us the flexibility to create our own initial configuration.

**Comment by rarkins** [comment]
I think this can be done in the regular `renovate` repo. The challenge is if the defaults get more complicated in future rather than the “fixed” config it is today. But pretty easy to make onboardingConfig to be a configurable option. Would you be wanting to set it via env?

**Comment by destroyerofbuilds** [comment]
Though not immediately related to this same issue, in the future we would like the ability to customize the initial configuration based on the type of project.

For example, for projects containing a `package.json`, we would want them setup with our _web_ configuration package, while, when it's supported, our Python projects would be setup with our _python_ configuration.

**Comment by destroyerofbuilds** [comment]
> I think this can be done in the regular renovate repo.

Sorry. Wasn't sure where to file this. It felt very much like a feature for those wanting to run their own instance (Especially large enterprises).

> Would you be wanting to set it via env?

Maybe that could work in the short-term. A stringified configuration?

> The challenge is if the defaults get more complicated in future rather than the “fixed” config it is today.

That's why I mentioned our future hopes regarding project-type based custom configuration. I'm not sure how a single environment variable would work for that.

**Comment by rarkins** [comment]
> It felt very much like a feature for those wanting to run their own instance (Especially large enterprises).

Agreed, I just meant that the logical place to solve it is within Renovate itself. This wrapper exists only to handle the specific authentication for GHE. So for example someone running GitLab may also want this.

> Maybe that could work in the short-term. A stringified configuration?

I thought env was your "long-term" solution too, that's why I asked. Yes, it could be solved so that you can configure this via `config.js` or stringified JSON object in env.

**Comment by destroyerofbuilds** [comment]
> So for example someone running GitLab may also want this.

I'll close this issue out and re-open it under the `renovate` repository.

> I thought env was your "long-term" solution too

Environment variables are how we configure Renovate in our environment. That is true. I just wasn't sure if a stringified environment variable could capture the requirements discussed above.
