### ISSUE TITLE
Processing Projects from a Queue

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/github-app-cli#15]
I would like to propose re-architecting this project to collect repositories on which this app has been installed, push those repositories into a queue (Such as [redis](https://redis.io/)), and then run a separate Renovate worker process that feeds from the queue.

Core benefits of this model:
1. Renovate can be scaled horizontally by spinning up additional Renovate worker processes that feed from the same queue.
1. Enables future support for Webhooks.
  2.1 Webhook POST body can be read, and the repository contained in the message placed into the queue.

Issues that need to be addressed:
1. A repository should only be queued once, and should not be removed from the queue until processing has been completed.
  1.1 This is to avoid multiple Renovate worker processes from processing the same repository simultaneously.

**Comment by rarkins** [comment]
This is pretty much how I have the Renovate App running very reliably (almost 4000 repositories). I have been planning to make this into a *commercial* (paid) “enterprise version” for those who want something more special than cron jobs. Any objections to that approach? I may give early adopters/testers very attractive rates :)

**Comment by bbatha** [comment]
No objections here, we'd be interested in that approach especially as we scale up.
